# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_formMain(object):
    def setupUi(self, formMain):
        formMain.setObjectName("formMain")
        formMain.resize(245, 163)
        self.pbAccept = QtWidgets.QPushButton(formMain)
        self.pbAccept.setGeometry(QtCore.QRect(20, 110, 91, 41))
        self.pbAccept.setObjectName("pbAccept")
        self.pbNewFile = QtWidgets.QPushButton(formMain)
        self.pbNewFile.setGeometry(QtCore.QRect(140, 110, 91, 41))
        self.pbNewFile.setObjectName("pbNewFile")
        self.tlSheet = QtWidgets.QLabel(formMain)
        self.tlSheet.setGeometry(QtCore.QRect(10, 10, 151, 16))
        self.tlSheet.setObjectName("tlSheet")
        self.comboBox = QtWidgets.QComboBox(formMain)
        self.comboBox.setGeometry(QtCore.QRect(10, 30, 221, 21))
        self.comboBox.setObjectName("comboBox")

        self.retranslateUi(formMain)
        QtCore.QMetaObject.connectSlotsByName(formMain)

    def retranslateUi(self, formMain):
        _translate = QtCore.QCoreApplication.translate
        formMain.setWindowTitle(_translate("formMain", "Form"))
        self.pbAccept.setText(_translate("formMain", "Reformat"))
        self.pbNewFile.setText(_translate("formMain", "Select File"))
        self.tlSheet.setText(_translate("formMain", "Available Sheets:"))
